import os

# Créer le dossier .streamlit s'il n'existe pas
if not os.path.exists('.streamlit'):
    os.makedirs('.streamlit')

# Créer le fichier secrets.toml avec vos clés
with open('.streamlit/secrets.toml', 'w') as f:
    f.write("""
[airtable]
AIRTABLE_API_KEY="pat7V90e4LZr6Nixi.0c9795b3f6b9842704e2c5d53cbaf0170ad296b9014ffb1c7d45b84b17c2f85c"